name: "Wait For Deploy"
author: "Sean Erswell-Liljefelt"
description: "Wait for and retrieve the status of a deployment, even from other workflows or projects"
branding:
  color: white
  icon: repeat
inputs:
  project:
    description: "The full owner/project path in which the deployment job runs"
    required: true
  token:
    description: "A secret holding a Personal Access Token or Similar with relevant role in the target repository"
    required: true
  deploy-id:
    description: "The ID of the deployment you wish to follow"
    required: true
  exit-code-on-failure:
    description: "The exit code to use for unsuccessful deployments DEFAULT=0"
    required: false
    default: "0"
  timeout:
    description: "How long to wait (seconds) before ending the job with result=timeout"
    required: false
    default: "300"
outputs:
  deploy-result:
    value: ${{ steps.wait.outputs.deploy-result }}
    description: "The outcome of the deployment job as reported by Github"
runs:
  using: "composite"
  steps:
    - name: Wait for Deployment
      shell: bash
      id: wait
      env:
        PROJECT: ${{ inputs.project }}
        TOKEN: ${{ inputs.token }}
        DEPLOY_ID: ${{ inputs.deploy-id }}
        EXIT_CODE: ${{ inputs.exit-code-on-failure }}
        TIMEOUT: ${{ inputs.timeout }}
      run: |
        timeout "$TIMEOUT"s ${{ github.action_path }}/main.sh